#!/usr/bin/env python3
"""
Compare the timing results in two Tatum timing graph echo files.

This is used to measure the accuracy of a timing estimate (for example, the
post-routing timing estimate made by the AP flow, written to
timing_graph.ap_post_routing_estimate.echo) against actual timing (for
example, the post-routing analysis, written to timing_graph.analysis.echo).

Both echo files must be over the same timing graph (i.e. generated from the
same atom netlist with the same options). This is verified before comparing.

Three scatter plots are generated, with the actual value on the x-axis and the
estimated value on the y-axis:
    - Connection delays: The delay of every routed interconnect edge.
    - Path delays: The setup data arrival time at every timing endpoint, for
      each clock domain pair.
    - Connection criticalities: The setup criticality of the sink of every
      routed interconnect edge, computed the same way as VPR (relaxed
      criticality).

Connections which are not routed through the general routing network are not
compared: connections driven by constant generators and connections to clock
pins (assuming ideal clocks). Their delays do not affect setup timing.

Echo files are generated by VPR using '--echo_file on'.

If the arc info file written alongside the estimate echo file is available,
the connection delay error is also broken down by arc type (how the estimate
was computed) and by (source pin, sink pin) pair, to find systematic biases.
"""

import argparse
import csv
import math
import os
import re
import sys
from collections import defaultdict, namedtuple

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # pylint: disable=wrong-import-position
import numpy as np  # pylint: disable=wrong-import-position


class TimingEcho:
    """The parts of a Tatum timing graph echo file needed for comparison."""

    def __init__(self):
        # Node id -> node type (e.g. "SINK", "IPIN").
        self.node_types = []
        # Edge id -> (edge type, src node, sink node, disabled).
        self.edges = []
        # Edge id -> max delay (seconds). Only for non-setup/hold edges.
        self.edge_max_delay = {}
        # (node, launch domain, capture domain) -> setup data arrival time.
        self.setup_arrival = {}
        # (node, launch domain, capture domain) -> setup data required time.
        self.setup_required = {}
        # (node, launch domain, capture domain) -> setup slack.
        self.setup_slack = {}
        # Nodes which are constant generators.
        self.constant_generators = set()

    def add_timing_constraints_record(self, record):
        """Add a constraint record from the timing_constraints section."""
        if record.get("type") == "CONSTANT_GENERATOR":
            self.constant_generators.add(int(record["node"]))

    def is_routed_connection(self, edge_id):
        """
        Returns True if the given edge is an interconnect edge which is routed
        through the general routing network (i.e. not driven by a constant
        generator and not connected to a clock pin).
        """
        edge_type, src_node, sink_node, disabled = self.edges[edge_id]
        if edge_type != "INTERCONNECT" or disabled:
            return False
        if src_node in self.constant_generators:
            return False
        return self.node_types[sink_node] != "CPIN"

    def add_timing_graph_record(self, record):
        """Add a node or edge record from the timing_graph section."""
        if "node" in record:
            assert int(record["node"]) == len(self.node_types)
            self.node_types.append(record["type"])
        elif "edge" in record:
            assert int(record["edge"]) == len(self.edges)
            self.edges.append(
                (
                    record["type"],
                    int(record["src_node"]),
                    int(record["sink_node"]),
                    record["disabled"] == "true",
                )
            )

    def add_delay_model_record(self, record):
        """Add an edge delay record from the delay_model section."""
        if "max_delay" in record:
            self.edge_max_delay[int(record["edge"])] = float(record["max_delay"])

    def add_analysis_result_record(self, record):
        """Add a setup tag or slack record from the analysis_result section."""
        if "node" not in record:
            # Edge slacks (only written if Tatum calculates them).
            return
        key = (
            int(record["node"]),
            int(record["launch_domain"]),
            int(record["capture_domain"]),
        )
        value = float(record.get("time", record.get("slack", "nan")))
        # Skip tags which do not correspond to timing paths (for example, the
        # tags of constant generators have infinite arrival times).
        if not math.isfinite(value):
            return
        tag_type = record.get("type")
        if tag_type == "SETUP_DATA_ARRIVAL":
            self.setup_arrival[key] = value
        elif tag_type == "SETUP_DATA_REQUIRED":
            self.setup_required[key] = value
        elif tag_type == "SETUP_SLACK":
            self.setup_slack[key] = value


def _parse_record(line):
    """Parse a line of 'key: value' pairs into a dictionary."""
    tokens = line.replace("\\", "").split()
    record = {}
    for i in range(0, len(tokens) - 1, 2):
        record[tokens[i].rstrip(":")] = tokens[i + 1]
    return record


def parse_timing_echo(filename):
    """Parse the timing graph, delay model and setup analysis results."""
    echo = TimingEcho()
    section_handlers = {
        "timing_graph": echo.add_timing_graph_record,
        "timing_constraints": echo.add_timing_constraints_record,
        "delay_model": echo.add_delay_model_record,
        "analysis_result": echo.add_analysis_result_record,
    }
    handler = None
    # Timing graph records span multiple lines (continued with a backslash).
    pending = ""

    with open(filename, "r", encoding="utf-8") as echo_file:
        for raw_line in echo_file:
            line = raw_line.rstrip("\n")
            if not line.strip():
                continue

            # Section headers are not indented.
            if not line.startswith(" "):
                handler = section_handlers.get(line.rstrip(":"))
                continue
            if handler is None:
                continue

            if line.endswith("\\"):
                pending += line + " "
                continue
            handler(_parse_record(pending + line))
            pending = ""

    return echo


def verify_same_timing_graph(actual, estimated):
    """Verify that two echo files are over the same timing graph."""
    if actual.node_types != estimated.node_types:
        sys.exit("Error: The timing graph nodes do not match between the echo files.")
    if actual.edges != estimated.edges:
        sys.exit("Error: The timing graph edges do not match between the echo files.")


def compute_setup_criticalities(echo):
    """
    Compute the setup criticality of every node with slack tags.

    This matches the relaxed criticality computed by VPR (see
    calc_relaxed_criticality in vpr/src/timing/timing_util.cpp): the maximum
    required time and worst slack are computed per clock domain pair over the
    timing endpoints (SINK nodes), slacks are shifted by the worst negative
    slack, and the criticality of a node is the maximum over its slack tags.
    """
    max_req = {}
    worst_slack = {}
    for (node, launch, capture), req in echo.setup_required.items():
        if echo.node_types[node] != "SINK":
            continue
        domain_pair = (launch, capture)
        max_req[domain_pair] = max(max_req.get(domain_pair, -math.inf), req)
    for (node, launch, capture), slack in echo.setup_slack.items():
        if echo.node_types[node] != "SINK":
            continue
        domain_pair = (launch, capture)
        worst_slack[domain_pair] = min(worst_slack.get(domain_pair, math.inf), slack)

    crits = {}
    for (node, launch, capture), slack in echo.setup_slack.items():
        domain_pair = (launch, capture)
        if domain_pair not in max_req or domain_pair not in worst_slack:
            continue
        req = max_req[domain_pair]
        if worst_slack[domain_pair] < 0:
            shift = -worst_slack[domain_pair]
            slack += shift
            req += shift
        if req > 0:
            crit = 1.0 - slack / req
        elif req == 0 and slack == 0:
            crit = 1.0
        else:
            continue
        crit = min(1.0, max(0.0, crit))
        crits[node] = max(crits.get(node, 0.0), crit)
    return crits


def collect_connection_delays(actual, estimated):
    """Collect the (actual, estimated) delays of all routed interconnect edges."""
    pairs = []
    for edge_id in range(len(actual.edges)):
        if not actual.is_routed_connection(edge_id):
            continue
        if edge_id in actual.edge_max_delay and edge_id in estimated.edge_max_delay:
            pairs.append(
                (actual.edge_max_delay[edge_id], estimated.edge_max_delay[edge_id])
            )
    return np.array(pairs).reshape(-1, 2)


def collect_path_delays(actual, estimated):
    """
    Collect the (actual, estimated) setup data arrival times at all timing
    endpoints (SINK nodes), per clock domain pair.

    The arrival time at an endpoint is the delay of the longest path ending
    there (including the launch clock latency).
    """
    pairs = []
    for key, actual_arrival in actual.setup_arrival.items():
        if actual.node_types[key[0]] != "SINK":
            continue
        if key in estimated.setup_arrival:
            pairs.append((actual_arrival, estimated.setup_arrival[key]))
    return np.array(pairs).reshape(-1, 2)


def collect_connection_criticalities(actual, estimated):
    """
    Collect the (actual, estimated) setup criticalities of the sinks of all
    routed interconnect edges.
    """
    actual_crits = compute_setup_criticalities(actual)
    estimated_crits = compute_setup_criticalities(estimated)
    sink_nodes = set()
    for edge_id, (_, _, sink_node, _) in enumerate(actual.edges):
        if actual.is_routed_connection(edge_id):
            sink_nodes.add(sink_node)
    pairs = []
    for node in sorted(sink_nodes):
        if node in actual_crits and node in estimated_crits:
            pairs.append((actual_crits[node], estimated_crits[node]))
    return np.array(pairs).reshape(-1, 2)


def parse_arc_info(filename):
    """
    Parse the arc info file written alongside the AP post-routing timing
    estimate echo file.

    Returns a dictionary from edge id to a dictionary with the arc type, net
    fanout and the source / sink pb_graph pins of the arc.
    """
    arc_info = {}
    with open(filename, "r", encoding="utf-8") as arc_info_file:
        for line in arc_info_file:
            if line.startswith("#") or not line.strip():
                continue
            record = _parse_record(line)
            arc_info[int(record["edge"])] = {
                "type": record["type"],
                "fanout": int(record["fanout"]),
                "src_pin": record["src_pin"],
                "sink_pin": record["sink_pin"],
            }
    return arc_info


def _strip_pin_indices(pin_name):
    """Remove the instance and pin indices from a pb_graph pin name."""
    return re.sub(r"\[\d+\]", "", pin_name)


def group_arc_errors(actual, estimated, arc_info):
    """
    Group the routed connections by (arc type, source pin, sink pin) and
    compute the delay error statistics of each group. Returns the groups as a
    list of rows, sorted by the magnitude of their total error.
    """
    groups = defaultdict(list)
    for edge_id in range(len(actual.edges)):
        if not actual.is_routed_connection(edge_id) or edge_id not in arc_info:
            continue
        if (
            edge_id not in actual.edge_max_delay
            or edge_id not in estimated.edge_max_delay
        ):
            continue
        info = arc_info[edge_id]
        key = (
            info["type"],
            _strip_pin_indices(info["src_pin"]),
            _strip_pin_indices(info["sink_pin"]),
        )
        groups[key].append(
            (
                actual.edge_max_delay[edge_id] * 1e9,
                estimated.edge_max_delay[edge_id] * 1e9,
            )
        )

    rows = []
    for (arc_type, src_pin, sink_pin), pairs in groups.items():
        pairs = np.array(pairs)
        error = pairs[:, 1] - pairs[:, 0]
        rows.append(
            {
                "arc_type": arc_type,
                "src_pin": src_pin,
                "sink_pin": sink_pin,
                "count": len(pairs),
                "actual_mean_ns": float(np.mean(pairs[:, 0])),
                "estimated_mean_ns": float(np.mean(pairs[:, 1])),
                "error_mean_ns": float(np.mean(error)),
                "error_total_ns": float(np.sum(error)),
            }
        )
    rows.sort(key=lambda row: abs(row["error_total_ns"]), reverse=True)
    return rows


def report_arc_error_breakdown(rows, output_dir, num_rows):
    """
    Print the connection delay error by arc type and the pin pairs with the
    largest total error, and write every pin pair group to a CSV file.
    """
    print("\nConnection delay error by arc type:")
    by_type = defaultdict(lambda: [0, 0.0])
    for row in rows:
        by_type[row["arc_type"]][0] += row["count"]
        by_type[row["arc_type"]][1] += row["error_total_ns"]
    for arc_type, (count, total) in sorted(by_type.items(), key=lambda kv: kv[1][1]):
        print(f"\t{arc_type:<18} count: {count:>7}  total error: {total:>10.1f} ns")

    print(f"\nConnection delay error by pin pair (top {num_rows} by total error):")
    print(
        f"\t{'arc type':<16} {'source pin':<24} {'sink pin':<24} {'count':>7} "
        f"{'actual':>8} {'est':>8} {'mean err':>9} {'total err':>10}"
    )
    for row in rows[:num_rows]:
        print(
            f"\t{row['arc_type']:<16} {row['src_pin']:<24} {row['sink_pin']:<24} "
            f"{row['count']:>7} {row['actual_mean_ns']:>8.3f} "
            f"{row['estimated_mean_ns']:>8.3f} {row['error_mean_ns']:>9.3f} "
            f"{row['error_total_ns']:>10.1f}"
        )

    os.makedirs(output_dir, exist_ok=True)
    csv_path = os.path.join(output_dir, "arc_error_by_pin_pair.csv")
    with open(csv_path, "w", encoding="utf-8", newline="") as csv_file:
        writer = csv.DictWriter(
            csv_file, fieldnames=list(rows[0].keys()) if rows else []
        )
        writer.writeheader()
        writer.writerows(rows)
    print(f"\tFull breakdown written to {csv_path}")


Comparison = namedtuple(
    "Comparison", ["file_name", "title", "axis_label", "unit_scale", "unit", "pairs"]
)
Comparison.__doc__ = (
    """A set of (actual, estimated) pairs to compare, and how to present them."""
)


def summarize(comparison):
    """Compute and print summary statistics of the (actual, estimated) pairs."""
    actual = comparison.pairs[:, 0] * comparison.unit_scale
    estimated = comparison.pairs[:, 1] * comparison.unit_scale
    unit = comparison.unit
    error = estimated - actual
    stats = {
        "count": len(actual),
        "pearson_r": (
            float(np.corrcoef(actual, estimated)[0, 1]) if len(actual) > 1 else math.nan
        ),
        "mean_error": float(np.mean(error)),
        "mean_abs_error": float(np.mean(np.abs(error))),
        "actual_max": float(np.max(actual)),
        "estimated_max": float(np.max(estimated)),
    }
    nonzero = actual > 0
    stats["median_ratio"] = (
        float(np.median(estimated[nonzero] / actual[nonzero]))
        if np.any(nonzero)
        else math.nan
    )

    print(f"{comparison.title}:")
    print(f"\tcount:                  {stats['count']}")
    print(f"\tPearson r:              {stats['pearson_r']:.4f}")
    print(f"\tmedian est/actual:      {stats['median_ratio']:.4f}")
    print(f"\tmean error (est-act):   {stats['mean_error']:.4f} {unit}")
    print(f"\tmean abs error:         {stats['mean_abs_error']:.4f} {unit}")
    print(
        f"\tmax actual / estimated: {stats['actual_max']:.4f} / "
        f"{stats['estimated_max']:.4f} {unit}"
    )
    return stats


def plot_scatter(ax, comparison, stats, title_prefix):
    """Draw a scatter plot of estimated vs actual with a y=x reference line."""
    actual = comparison.pairs[:, 0] * comparison.unit_scale
    estimated = comparison.pairs[:, 1] * comparison.unit_scale
    ax.scatter(
        actual,
        estimated,
        s=3,
        alpha=0.25,
        linewidths=0,
        color="#2a6fdb",
        rasterized=True,
    )
    lim_lo = min(0.0, float(np.min(actual)), float(np.min(estimated)))
    lim_hi = max(float(np.max(actual)), float(np.max(estimated))) * 1.05
    ax.plot(
        [lim_lo, lim_hi], [lim_lo, lim_hi], color="#555555", linewidth=1, linestyle="--"
    )
    ax.set_xlim(lim_lo, lim_hi)
    ax.set_ylim(lim_lo, lim_hi)
    ax.set_aspect("equal")
    ax.set_xlabel(f"Actual {comparison.axis_label}")
    ax.set_ylabel(f"Estimated {comparison.axis_label}")
    ax.set_title(title_prefix + comparison.title)
    ax.grid(True, linewidth=0.3)
    ax.text(
        0.03,
        0.97,
        f"n = {stats['count']}\nr = {stats['pearson_r']:.3f}\n"
        f"median est/act = {stats['median_ratio']:.3f}",
        transform=ax.transAxes,
        verticalalignment="top",
        fontsize=8,
        bbox={"boxstyle": "round", "facecolor": "white", "alpha": 0.8},
    )


def write_plots(comparisons, output_dir, title_prefix):
    """
    Print summary statistics and write a scatter plot for each comparison, as
    well as a combined figure with all comparisons side-by-side.
    """
    os.makedirs(output_dir, exist_ok=True)
    fig_all, axes = plt.subplots(1, len(comparisons), figsize=(6 * len(comparisons), 6))
    for ax_all, comparison in zip(axes, comparisons):
        if len(comparison.pairs) == 0:
            print(f"{comparison.title}: no data to compare")
            continue
        stats = summarize(comparison)
        plot_scatter(ax_all, comparison, stats, title_prefix)

        fig, ax = plt.subplots(figsize=(6, 6))
        plot_scatter(ax, comparison, stats, title_prefix)
        fig.tight_layout()
        fig.savefig(os.path.join(output_dir, f"{comparison.file_name}.png"), dpi=150)
        plt.close(fig)

    fig_all.tight_layout()
    fig_all.savefig(os.path.join(output_dir, "timing_estimate_accuracy.png"), dpi=150)
    plt.close(fig_all)
    print(f"\nPlots written to {output_dir}")


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Compare the timing results of two Tatum timing graph echo files."
    )
    parser.add_argument(
        "actual_echo",
        help="Echo file with the actual timing (e.g. timing_graph.analysis.echo).",
    )
    parser.add_argument(
        "estimated_echo",
        help="Echo file with the estimated timing "
        "(e.g. timing_graph.ap_post_routing_estimate.echo).",
    )
    parser.add_argument(
        "--output_dir",
        default=".",
        help="Directory to write the plots to (default: .).",
    )
    parser.add_argument("--title", default="", help="Title prefix added to the plots.")
    parser.add_argument(
        "--arc_info",
        default=None,
        help="Arc info file written with the estimate echo file, used to break "
        "down the error by arc type and pin pair (default: <estimated_echo>.arc_info "
        "if it exists).",
    )
    parser.add_argument(
        "--num_rows",
        type=int,
        default=15,
        help="Number of pin pairs to print in the error breakdown (default: 15).",
    )
    args = parser.parse_args()

    print(f"Parsing {args.actual_echo}...")
    actual = parse_timing_echo(args.actual_echo)
    print(f"Parsing {args.estimated_echo}...")
    estimated = parse_timing_echo(args.estimated_echo)
    verify_same_timing_graph(actual, estimated)
    print(f"Timing graph: {len(actual.node_types)} nodes, {len(actual.edges)} edges\n")

    comparisons = [
        Comparison(
            "connection_delay",
            "Connection Delay",
            "delay (ns)",
            1e9,
            "ns",
            collect_connection_delays(actual, estimated),
        ),
        Comparison(
            "path_delay",
            "Endpoint Path Delay",
            "arrival time (ns)",
            1e9,
            "ns",
            collect_path_delays(actual, estimated),
        ),
        Comparison(
            "connection_criticality",
            "Connection Criticality",
            "criticality",
            1.0,
            "",
            collect_connection_criticalities(actual, estimated),
        ),
    ]
    write_plots(comparisons, args.output_dir, f"{args.title}: " if args.title else "")

    arc_info_file = args.arc_info
    if arc_info_file is None and os.path.exists(args.estimated_echo + ".arc_info"):
        arc_info_file = args.estimated_echo + ".arc_info"
    if arc_info_file is not None:
        rows = group_arc_errors(actual, estimated, parse_arc_info(arc_info_file))
        report_arc_error_breakdown(rows, args.output_dir, args.num_rows)


if __name__ == "__main__":
    main()
